/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>



int main(void)
{
	uint32_t *AHB1ENR =(uint32_t*)0x40023830;
	//base address-0x4002 3800+ 0x30 = 0x40023830;
	uint32_t *MODER = (uint32_t*)0x40020000;
	//0x4002 0000-
	uint32_t *ODR = (uint32_t*)0x40020014;
	//0x4002 0000 -Address offset: 0x14 -0x40020014;

	*AHB1ENR |=0x01;
	*MODER &= 0xFFFFF3FF;

	*MODER |= 0x00000400;

	*ODR |= 0x20;

	for(;;);
}
